#!/bin/bash

usage() {
        echo "${0/*\/} <threshhold#>"
}

if [ $# -eq 0 ]; then
        usage 1>&2 ;
        exit 1;
fi

THRESHHOLD=$1

case ${THRESHHOLD#[-+]} in
        *[!0-9]* | '')
                usage 1>&2 ;
                echo $THRESHHOLD is not a number.
                exit 2;;
        * )
esac
